services:

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - movie_book_network

  redis:
    image: redislabs/redismod
    ports:
      - "6379:6379"
    networks:
      - movie_book_network

  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    networks:
      - movie_book_network
  
  directus:
    image: directus/directus
    ports:
      - "8055:8055"
    depends_on:
      - database
      - redis
    environment:
      SECRET: "${SECRET}"

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "${POSTGRES_DB}"
      DB_USER: "${POSTGRES_USER}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://redis:6379"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://localhost:3000"

      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
    networks:
      - movie_book_network
    
  api:
    build:
      context: ./server
      target: builder
    stop_signal: SIGINT
    environment:
      DB_DATABASE: "${POSTGRES_DB}"
      DB_USER: "${POSTGRES_USER}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}"
    ports:
      - '5000:5000'
    depends_on:
      - redis
      - database
    networks:
      - movie_book_network
    volumes:
      - ./data:/data


networks:
  movie_book_network: